version: '3'

services:
  db:
    image: mongo:latest
    container_name: db
    restart: always
    ports:
      - 27017:27017
  api:
    container_name: api
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 5000:5000
    env_file: ./config/config.env
    depends_on:
      - db
